### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by MaxCrazy1101** [slicol/Games101-Homework-Win#1]
![image](https://user-images.githubusercontent.com/35657483/166655898-71dd6b8a-ff96-4133-83ec-9154761acb54.png)
我还是没办法编译通过，是clang不行吗还是要其他的配置

**Comment by xjs0227** [comment]
请问解决了吗

**Comment by MaxCrazy1101** [comment]
> 请问解决了吗

no，装虚拟机了，用的vm，你可以去知乎上找配置方法
